#!/bin/bash

dictionary=data/local/dict_phn
train=data/train
test=data/test
dev=data/dev
lang_model=data/local/lang
lang=data/lang_phn
lang_test=data/lang_phn_test
beam=17.0
nj=1
min_lmwt=5
max_lmwt=10
oovwords=Yes
apply_fmllr=Yes
applylmoptimize=Yes
apply_cmvn=Yes
lexicon=swbd
experiment_status=1
